import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav/Nav';
import RecoilProvider from '@/components/provider/RecoilProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    userScalable: false,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <RecoilProvider>
            <html lang="en">
                <body className={inter.className}>
                    <Nav />
                    {children}
                </body>
            </html>
        </RecoilProvider>
    );
}
