import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RecoilProvider from '@/components/provider/RecoilProvider';
import SafetyAreaProvider from '@/components/provider/SafetyAreaProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    userScalable: false,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <RecoilProvider>
            <SafetyAreaProvider>
                <html lang="ko">
                    <body className={inter.className}>
                        <div className="flex flex-col min-h-screen">{children}</div>
                    </body>
                </html>
            </SafetyAreaProvider>
        </RecoilProvider>
    );
}
